// Automatically generated by astro-icon
// d2279d862bda1b47342babf502d990760cce3825dc7d58aeeb3553f3cd48e1fe

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "contact/email"
		| "contact/home"
		| "contact/phone"
		| "logo"
		| "services/crm-service"
		| "services/mobile-service"
		| "services/web-service"
		| "social/github"
		| "social/instagram"
		| "social/linkedin"
		| "technologies/angular"
		| "technologies/flutter"
		| "technologies/nest"
		| "technologies/react"
		| "ui/menu";
}